###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Josef Malý'
comments_config = {'hypothesis': False, 'utterances': {'repo': 'Smichovska-SPS/notes'}}
copyright = '2022'
exclude_patterns = ['**.ipynb_checkpoints', './README.md', './test.ipynb', '.DS_Store', 'Thumbs.db', '_build']
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 30
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = ''
html_logo = 'logo.jpg'
html_sourcelink_suffix = ''
html_static_path = ['_static']
templates_path = ["_templates"]
html_theme = 'furo'
html_theme_options = {'announcement': "<p'>⚠️ Tyto skripta jsou v raném vývoji ⚠️</p>",
                    "source_repository": "https://github.com/Smichovska-SPS/notes",
                    "source_branch": "main"}
html_title = 'Programování a vývoj aplikací'
jupyter_cache = ''
jupyter_execute_notebooks = 'force'
language = 'csharp'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
